### ISSUE TITLE
Join lanqiu

### ISSUE THREAD

**Issue by taxio** [StudioAquatan/Saffron#123]
- [ ] Docker install
- [ ] Readmeに従ってdev環境を起動させてみる
- [ ] http://localhost:8000/admin/ にアクセスできる
- [ ] http://localhost:8000/swagger/ にアクセスできる
- [ ] `/petals/` 以下でアプリを起動させられる(README参考)

**Comment by lanqiugit** [comment]
Readmeの

```bash
# .env.*をコピーして作成
$ make env
# .venvの作成，node_modulesの作成，イメージをPull
$ make deps
```

の部分ができないのですが, どうしたらよいのでしょうか？

現段階は, Dockerのインストールが完了し, Saffronのdevを適当なフォルダに保存したところまできています.
問題となっているのは, そのフォルダ内でmakeコマンドを実行した場合, 
```bash
C:\Users\...\Saffron_env>make env
ファイルが見つかりません - *.css
ファイルが見つかりません - *.json
! の使い方が誤っています。
make: *** [guard-env-qa] エラー 255
```
となり, makeが正しく実行しません.
makeコマンドはGnuWinのを入れました.

**Comment by taxio** [comment]
@pddg

**Comment by pddg** [comment]
Windows環境だとうまくコマンドの解釈ができないっぽい．実際やってることはサンプルのenvファイルをあちこちにコピーすることだけだからそのステップは飛ばして良い．
`make deps`はpipenv installとyarn installしてるだけだから，それも各ディレクトリで走らせるだけでok．フロントエンドの開発だけならpipenv installも不要．

**Comment by lanqiugit** [comment]
```make deps```を各ディレクトリで走らせるということでしょうか？

```bash
C:\Users\...\Saffron_env\calyx> make deps
make: *** ターゲット `deps' を make するルールがありません.  中止.
```
になりました.

**Comment by pddg** [comment]
いや，petalsの中でyarn installすれば大丈夫

**Comment by lanqiugit** [comment]
dev環境になっているかがわかりませんが, ```yarn start```で一応Saffronのトップページを開くことはできました.
ただ, adminとswaggerのページはSaffronのトップバーだけ表示されている画面になっているので, 開けていないです.
make migrationなどをする必要がある感じなのでしょうか？

**Comment by pddg** [comment]
バックエンドのAPIは`yarn start`で建たないのでdocker-composeを使うか，自分でDjangoアプリケーションを建てる必要があります．

## 共通

開発環境用のenvファイルを用意する．`petals`，`calyx`，`bulb`それぞれのディレクトリ内にサンプルのenvファイルがあるのでそれを元に`.env.dev`を各ディレクトリに作成する．

## docker-composeを使う場合

```cmd
> make start-dev
```

で建ちます．ただフロントエンドのコンテナ（petals）も建ってしまいます．petalsは内部にソースコードをマウントして`yarn start`するので，ホットリロードが使えますが，デバッグ等がしづらいので基本開発では使わないかも知れません．

フロントエンドのコンテナのみ起動しないなら

```cmd
> docker-compose -f docker-compose.dev.yml up -d calyx bulb
```

でデータベースとバックエンドAPIが起動します．

データベースのマイグレーションは以下で実行できます

```cmd
> make migrate-dev
```

管理コマンドの実行は

```cmd
> make manage-dev args="createsuperuser"
```

## 自分でDjangoアプリケーションを建てる場合

MySQLコンテナは以下で建ちます．

```cmd
> make db
```

`calyx`ディレクトリ以下で`pipenv install`して環境を整え，

```cmd
> pipenv shell
> python manage.py migrate
> python manage.py createsuperuser
> python manage.py runserver
```

で起動できます．

**Comment by pddg** [comment]
フロントエンドは`:8080`，バックエンドのAPIは`:8000`でlistenしていることに注意してください

**Comment by lanqiugit** [comment]
```docker-compose```や```pipenv shell```などは使えますが, ```make```が使えなくて先に進めないです...

**Comment by pddg** [comment]
じゃあMakefile読んで直接コマンド実行してみて！(笑)

**Comment by lanqiugit** [comment]
やってみます！（笑）

**Comment by lanqiugit** [comment]
Makefileのコマンドを直接実行することはできました.
また, localhost:8080でSaffronのページを開くこともできました.
しかし, adminとswaggerのページはSaffronのトップバーだけが出るページになってしまうのですが, これはどこが原因になっているのでしょうか？

**Comment by taxio** [comment]
migrationとuser作成の後
- http://localhost:8000/admin/
- http://localhost:8000/swagger/

にアクセスすればいけるはず．
ポートはあってますか？

**Comment by lanqiugit** [comment]
```migrate```し, ```createsuperuser```でID, PW作成後, 8000番にアクセスしますが, 
```このページを表示できません```となります.

ここまで行ったことですが,
* petalsに```yarn install```を実行
* petals, bulb, calyxの.env.sampleを.env.devに変更(calyxディレクトリの.env.devのCALYX_SECRET_KEY=をCALYX_SECRET_KEY=abcに編集)
* ```docker-compose -f docker-compose.dev.yml build```(make build-dev)を実行
* ```docker-compose -f docker-compose.dev.yml up -d```(make start-dev)を実行
* ```docker-compose -f docker-compose.dev.yml exec calyx python manage.py migrate```(make migrate-dev)を実行
* ```docker-compose -f docker-compose.dev.yml exec calyx python manage.py createsuperuser```(make manage-dev args="createsuperuser")を実行し, IDとPWを設定
* http://localhost:8080/ の正常なページ表示を確認
* http://localhost:8000/admin/ のページにアクセスするもページが表示できません

どこか抜けがあるのでしょうか？

**Comment by pddg** [comment]
僕の手元でもたまにそれが起きました．とりあえず #132 で依存関係をごそっとアップデートしたので，マージ後にもう一度試してもらえないかな．

**Comment by lanqiugit** [comment]
一度すべて削除し, アップデート後のdevでpetalsの```yarn install```から始めましたが, 
http://localhost:8080/ の正常なページ表示の確認まではできるものの, 
http://localhost:8000/admin/ , http://localhost:8000/swagger/ のページが表示できませんでした.

**Comment by pddg** [comment]
[msys2](http://www.msys2.org/)のmakeは普通に動作して使えた（ファイルが見つかりませんは依然として出るが，別に影響なく動く）

以下メモ

不要なGnuWinのmakeは消しておく．

```cmd
> choco install msys2
> C:\tools\msys64\mingw64.exe
```

```bash
$ pacman -Syu
$ pacman -Su
# デフォルトで入ってた気がするけど
$ pacman -S make
```

Windowsのユーザ環境変数に以下のパスを追加する

- `C:\tools\msys64\usr\bin`

コマンドプロンプトなりPowerShellなりを起動してSaffronのリポジトリまで移動，`make image`してみる．

**Comment by lanqiugit** [comment]
動くようにしてもらいました.
お騒がせして申し訳ございません.

原因
* gnu makeがちゃんと動作していない → msys2のmakeで解決
* wslのPATHが魔境 → 頑張る
