### ISSUE TITLE
ユーザがその課程の要求を満たしているかどうかをチェックするエンドポイント

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/Saffron#126]
課程ごとに表示設定が存在し，その要件を満たすことが出来ない場合，ユーザは希望調査の結果を取得する事が出来ない（403が返る）．

エラーメッセージ内にはその情報を付加しているが，フロントエンド側でそのハンドリングをすることは困難になり得る．

このAPIでユーザの情報の提出状況を確認できるようにする．

状態として下記の3種類を想定

- `ok`: 閲覧資格を満たしている
- `insufficient`: 閲覧資格を満たしていない
- `pending`: 課程への加入待ち

## 案1

ユーザエンドポイントに生やす

- `/me/status/`

返り値

```python
{
  # 全体の状態（複数課程を想定）
  "status": "ok",
  "status_message": "閲覧資格を満たしています",
  # 各課程ごとの状態
  "detail": [
    {
      "course_id": 1,
      "status": "ok",
      "status_message": "閲覧資格を満たしています",
      "detail": {
        "gpa": true,
        "screen_name": true,
        "rank_submitted": true
      }
    }
  ]
}
```

## 案2

課程のエンドポイントに生やす

- `/courses/<course_pk>/status/`

```python
{
  "status": "ok",
  "status_message": "閲覧資格を満たしています",
  "detail": {
    "gpa": true,
    "screen_name": true,
    "rank_submitted": true
  }
}
```

**Comment by pddg** [comment]
@taxio どっちが良いと思う？

**Comment by taxio** [comment]
案2かな
バックエンドは複数課程参加ができることを前提として開発が続いているから，案2にする方が自然な気がするし，何よりRESTっぽい

**Comment by pddg** [comment]
OK
