### ISSUE TITLE
JWT認証の仕組みが変わった

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/Saffron#138]
refs #132 

上記PRでdjoserをアップデートした．これによってJWT認証のレスポンスが変わった．
django-rest-framework-jwtから[davesque/django-rest-framework-simplejwt](https://github.com/davesque/django-rest-framework-simplejwt)に．

## 変更点

- `/auth/jwt/create/`
  - リフレッシュトークンとアクセストークンが分離された

レスポンス

```python
{
    "access": "アクセストークン",
    "refresh": "リフレッシュトークン"
}
```

- `/auth/jwt/refresh/`
  - アクセストークンではなくリフレッシュトークンを送信して新しいアクセストークンを得る

リクエスト

```python
{
    "refresh": "リフレッシュトークン"
}
```

レスポンス

```python
{
    "access": "アクセストークン"
}
```

### フロントエンド

認証の仕組み全て

### バックエンド

有効期限などの設定項目が変化している可能性

**Comment by taxio** [comment]
今までの方法で認証情報付けてPOSTしても `invalid payload` と言われる
```bash
$ curl -X GET "http://localhost:8000/me/" \                                                                                        
                                -H "accept: application/json" \
                                -H "Content-Type: application/json" \
                                -H "Authorization: JWT {{access token}}"
{"detail":"Invalid payload."}
```

公式ドキュメントでは`Authorization: Bearer {{access token}}` だったのでそっちでやってみても，`認証情報が含まれていません`と返ってくる

**Comment by taxio** [comment]
公式のREADMEに従って，`settings.py`を修正する必要性がありそう．
https://github.com/davesque/django-rest-framework-simplejwt#settings

**Comment by pddg** [comment]
認証バックエンドの変更を加えることで認証が通るようになった．`Bearer`と`JWT`どっちでもいけるけど，`JWT`に直した方がいいよね？

**Comment by taxio** [comment]
そうっすね
