### ISSUE TITLE
Common password validation api

### ISSUE THREAD

**Issue by taxio** [StudioAquatan/Saffron#143]
Djangoの`CommonPasswordValidator`に則ったpassword validationをするAPIを作成する．

フロント側でバリデーションを完全にすり合わせるのは現実的ではない．
課程作成のフロー(3step)において，PINコード入力(1step目)と全体のデータをPOST(3step目)するまでが遠いので，1step目終了時に一度バックエンド側にバリデーション処理を投げる必要がある．

**Comment by pddg** [comment]
もう少し一般化してパスワードのチェックAPIにしてしまおうかな

- POST `/password/validate/`

リクエスト

```python
{
    # userまたはpin_code
    "type": "pin_code",
    "password": "パスワード"
}
```

レスポンス

status_code == 201
```python
{
    "type": "pin_code"
    "password": "ok"
}
```

または

status_code == 400
```python
{
  "password": [
    "このパスワードは短すぎます。最低 4 文字以上必要です。",
    "このパスワードは一般的すぎます。"
  ]
}
```

**Comment by taxio** [comment]
いいと思う
