### ISSUE TITLE
パスワードのバリデーション

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/Saffron#28]
フロントエンドで多少バリデーションを行う

- [x] 二回入力させて一致するか
- [x] 使用不可文字が含まれていないかのチェック
- [x] 長さのチェック
  - ユーザに設定するパスワードは最低8文字以上
  - 課程に参加するためのPINコードは最低4文字以上

**Comment by taxio** [comment]
@pddg 
使用不可文字とかについてここに残しといて

**Comment by pddg** [comment]
Keycloakを使用するなら設定は自由にいじれる． ここを参照
https://www.keycloak.org/docs/latest/server_admin/index.html#_password-policies

**Comment by taxio** [comment]
@pddg 
使用可能文字どうしよう

**Comment by pddg** [comment]
Djangoのドキュメントを読み込んでみたけど「使用できない文字種」とかそういう類いのものは発見できなかった．要するになんでも良いっぽい．
Djangoがチェックしているのはユーザ名に類似してないかとか，よくあるパスワードになってないかとか，長さはどうとか，そういうルールだけ．

**Comment by taxio** [comment]
なるほど

**Comment by pddg** [comment]
バックエンド側としては使用できない文字種はないとしか言えない．ただ制限した方がいいとは思うし，`[a-zA-Z0-9,\.\#\$\%\^\&\)\(\\\[\]\{\}\@\=\+\-\_]`くらいでいいんじゃないか．

**Comment by pddg** [comment]
どうせそんな強力なパスワードを設定するユーザはいないという前提でもっと文字種絞っても良いかもしれない．文字種増やすより長くした方がいいという話もあるし．

**Comment by taxio** [comment]
こっちはなんでもいいよ

**Comment by pddg** [comment]
ASCII印字可能文字とかがちょうど良さそうだけど，ユーザに提示しても理解してくれなさそう…

**Comment by pddg** [comment]
`python3 -c "import string; print(string.ascii_letters + string.digits + string.punctuation)"`して出てくる文字一覧でどうだろうか．

**Comment by taxio** [comment]
「英数字および記号(`,.#$%^&)(\[]{}@=+-_`)が使用可能」みたいな表現にするか．
英字・数字・記号を1つずつ含まなくてはいけないって制約はいらないか

**Comment by pddg** [comment]
含む文字種の指定は逆にセキュリティ的に弱くなるって言うのが最近の見解だったはず

**Comment by pddg** [comment]
メモ：pythonで印字可能なascii文字のバリデーションには標準ライブラリの`curses.ascii.isgraph()`が使えそう
