### ISSUE TITLE
MockAPI

### ISSUE THREAD

**Issue by taxio** [StudioAquatan/Saffron#30]
![saffron-er](https://user-images.githubusercontent.com/15796172/41757090-d3dea97e-761a-11e8-9a4a-eab72fecf745.png)

**Comment by taxio** [comment]
Golangで書くぞ俺は！！！！

**Comment by pddg** [comment]
OpenID Connectの旅に出ます。探さないでください。

**Comment by taxio** [comment]
dockerの環境が整ったので必要ない
