### ISSUE TITLE
論理削除したユーザの情報を保持する期限を決める

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/Saffron#46]
永久に持っておくわけにはいかない．30日とか？
ただ消すトリガーが難しい（毎日cronで叩くとか？）

**Comment by taxio** [comment]
まぁ、それがいいだろうね。
残すのはメールアドレスくらいで、他の情報は論理削除時に消しておきたい。

**Comment by pddg** [comment]
どこまで情報を残すか悩む．所属していた課程の情報とか残しておかないと意味が無い気もする．

**Comment by pddg** [comment]
ここ（refs #43 ）にあるように，パスを知っていれば適当な課程にJOINしまくってAdminの情報を見れることが問題なので，課程の情報は保持しないといけない．課程から脱退するのをどうするんだみたいな話もあるけど，レアケースなので無視しても良いんじゃないか．

**Comment by taxio** [comment]
- GPA
- 希望研究室

だけ消すか
