### ISSUE TITLE
APIサーバのドメイン

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/Saffron#48]
- 別のサブドメインで公開
    - 例：`api.saffron.aquatan.studio`
- 同一サブドメインで別ディレクトリで公開
    - 例：`saffron.aquatan.studio/api/`

どっちの方がいいだろう？

**Comment by taxio** [comment]
サブドメインで

**Comment by pddg** [comment]
ローカルの開発時はどうする？Dockerコンテナを別ポートで待ち受け？

**Comment by taxio** [comment]
Routingのコンフリクト気にするよりそっちの方が楽かな〜
