### ISSUE TITLE
各課程の管理者の情報流出を避けることが難しい

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/Saffron#71]
## 理由

- 課程に参加するためには，各課程に設定されたPINコードを知る必要がある
- それを設定したのはその課程を作成した管理者のみ
- 課程の管理者の情報公開をその課程の参加希望者に限定する場合，どこかでその情報を記憶しなければならない
  - そうでない場合，全員に公開する事になってしまう
- 現状のデータ構造ではこれを記憶することが難しい

## 対処法

- ユーザと課程を繋いでいる中間テーブルを自分で定義し直し，`active`フラグを立てる
  - 参加希望or参加した後にユーザ削除 -> `active`を`False`に
  - PINコードを入力して参加 -> `active`を`True`に
  - メリット
    - 現状のデータ構造から大きく変化しない
  - デメリット
    - 中間テーブルを自分でハンドリングしないといけない（中間テーブルでのフィルタの仕方がよく分からない）
    - 間違って課程を選択した場合の対処をどうするかを考えないといけない
- `join_history`みたいなテーブルを作る
  - ユーザの参加希望履歴を取る．
  - メリット
    - 頻繁に課程を出入りするユーザを検出できる
    - 管理者による承認制に切り替えることも簡単にできる可能性がある？
  - デメリット
    - これRDBでやることなのか？

**Comment by taxio** [comment]
承認制にすると，管理者1人で他何十人を承認しなきゃいけないから，ユーザーフローとしてよくない(Joinさせるためのショートカットとかを用意しないといけなくなって，それってPINじゃんって戻ってくる)
けど，後者のほうが処理的にはキレイな気がする．リレーション図ちゃんと見てないから何とも言えないけど．

間違えるなんて考えにくいし，いっその事，一度課程を設定したらもう変えられないって制約つけても良い気がする．
まぁ間違えられたらお問い合わせフォームからどうにか申請してもらう...

**Comment by pddg** [comment]
一つ思ったのは，同じ課程に所属する人間の学生番号って連続しているので，いわゆるホワイトリスト制にすることも可能なんじゃ無いかってこと．たぶんだけど，うちの大学で配属時に課程全体が対象とならないのは応用化学系だけな気がする．
b800001 ~ b8000xxxまで+いくつかの例外くらいで十分まかなえるような気がしている．

ただそれを記述させる良い方法が思い浮かばない…

**Comment by taxio** [comment]
ホワイトリストは良さげな気がするけど，リストに無い人(過年度生)がSaffronに登録した場合，参加できるコースが存在しない and コースの管理者も分からないからどうしようもないって状況が生まれない？

**Comment by pddg** [comment]
管理者が後からホワイトリストを編集できるようにすれば良い気はする．過年度生がちゃんと意思疎通を図れているという前提になってしまうけど…

**Comment by taxio** [comment]
じゃあホワイトリストでも良い気がする．

ただ，悪意ある人間に管理者取られた時の対策をしないといけない．

**Comment by pddg** [comment]
それはPINコードでも同じでは？現状お問い合わせしてもらうか，新しく課程を作ってもらうしか無さそう．

ホワイトリストにする場合もはやPINコードが不要になってしまう…実装が…

**Comment by taxio** [comment]
まとめると，
- 課程選択時に，その課程の管理者の情報は見えない
- 選択後，Joinするには管理者によるホワイトリストに登録またはPINの入力が必要
- ユーザーは何度でも課程を抜けたり入ったりすることができる
- 悪意あるユーザーが課程の管理者を取得した場合，有志による別課程を作成するか，お問い合わせによって運営が対処
  - 運営が対処する場合は別途何が不正行為に当たるか定義しないといけない

ということ？
それならPINのみでいいんじゃない？

**Comment by pddg** [comment]
課程を作成する時にb800001 ~ b8000xxxとb700000xは許可みたいなのを設定できると大多数のユーザはPINコード無しにジョインできて楽だなとちょっと思った．もちろんそれ以外のユーザを許可するには追加で設定が必要にはなる．
ただ面倒臭くなるし，結局それを使わない場合にはPINコードでの対応になるだけだからややこしくなるし，今は良いかな．要望があればくらいで…

ユーザの選択結果をDBで保持，次回以降はそれを参照して課程選択画面ではなくPINコードの入力画面を出す？

**Comment by pddg** [comment]
バックエンド的には複数課程へのジョインも許容できるけど，結局複数課程へのジョインを許容してしまうとどんな情報流出対策も意味を成さない気がしてきた．ジョインするための情報を管理者のみが握っている以上，参加希望ユーザはその情報にアクセスしないと行けない…

**Comment by taxio** [comment]
ホワイトリストはfuture workで

うーん，管理者の情報を出さない今となっては，選択結果をDBで持つ意味はあまり無いんじゃないかな？
もちろん1画面分ショートカットできるっていうメリットはあるけど，それを実現するための実装・整合性の確保の労力を考えると今は見合わない．

**Comment by pddg** [comment]
PINコードの情報はどうせユーザ側でLINEグループとかで発信してくれる気がしてきた

**Comment by pddg** [comment]
ユーザ側で情報を事前に共有してくれるという前提なら管理者の情報を出す必要は無いし，各課程の選択画面でPINコードを要求するだけで良い感じはする．

**Comment by taxio** [comment]
自分もそれで良いと思う

**Comment by pddg** [comment]
じゃあ

- 管理者情報の露出は無し
- 課程選択時にPINコードを要求

でいこう．課程の脱退や複数課程へのジョインを許可するかは悩みどころ…とりあえず今のところは無しでいこう．

**Comment by pddg** [comment]
管理者情報の露出がない場合，論理削除の必要が無い…？

refs #43
refs #46  
refs #74

**Comment by taxio** [comment]
.....!!!!!!!!!!!!!!

**Comment by pddg** [comment]
実装削減のチャンス

**Comment by taxio** [comment]
複数Joinは無しとして，脱退は気軽にできてほしい気がする．
PINを取得できる時点でその人がその課程に入るべき人間っていうのはある程度担保できてるはず(リセマラの危険性が低い)だし，もうサービス使いたくなくなった時に他人に自分の情報が見え続けるのも嫌だろうし．

**Comment by pddg** [comment]
- 複数課程へのジョインは無し
- 脱退は許可

了解．
